export const p_data = [
    {
    "id": 1,
    "product_name": "Automotive",
    "product_price": "$2.96",
    "available": false
  }, {
    "id": 2,
    "product_name": "Samsung Tablet",
    "product_price": "$9.81",
    "available": true
  }, {
    "id": 3,
    "product_name": "Clothing",
    "product_price": "$0.57",
    "available": true
  }, {
    "id": 4,
    "product_name": "Health",
    "product_price": "$1.57",
    "available": true
  }, {
    "id": 5,
    "product_name": "Tools",
    "product_price": "$3.24",
    "available": true
  }, {
    "id": 6,
    "product_name": "Outdoors",
    "product_price": "$6.37",
    "available": false
  }, {
    "id": 7,
    "product_name": "Health",
    "product_price": "$0.43",
    "available": true
  }, {
    "id": 8,
    "product_name": "Kids",
    "product_price": "$9.85",
    "available": true
  }, {
    "id": 9,
    "product_name": "Water Purifier",
    "product_price": "$6.19",
    "available": true
  }, {
    "id": 10,
    "product_name": "Samsung Tablet",
    "product_price": "$6.92",
    "available": false
  }, {
    "id": 11,
    "product_name": "Outdoors",
    "product_price": "$6.03",
    "available": false
  }, {
    "id": 12,
    "product_name": "Clothing",
    "product_price": "$7.94",
    "available": false
  }, {
    "id": 13,
    "product_name": "Home",
    "product_price": "$1.37",
    "available": false
  }, {
    "id": 14,
    "product_name": "Health",
    "product_price": "$9.26",
    "available": true
  }, {
    "id": 15,
    "product_name": "Beauty",
    "product_price": "$0.58",
    "available": true
  }, {
    "id": 16,
    "product_name": "Tools",
    "product_price": "$8.96",
    "available": false
  }, {
    "id": 17,
    "product_name": "Music",
    "product_price": "$4.97",
    "available": false
  }, {
    "id": 18,
    "product_name": "Outdoors",
    "product_price": "$3.73",
    "available": false
  }, {
    "id": 19,
    "product_name": "Shoes",
    "product_price": "$8.25",
    "available": true
  }, {
    "id": 20,
    "product_name": "Toys",
    "product_price": "$7.53",
    "available": false
  }, {
    "id": 21,
    "product_name": "Beauty",
    "product_price": "$2.05",
    "available": true
  }, {
    "id": 22,
    "product_name": "Tools",
    "product_price": "$2.37",
    "available": false
  }, {
    "id": 23,
    "product_name": "Movies",
    "product_price": "$6.40",
    "available": true
  }, {
    "id": 24,
    "product_name": "Water Purifier",
    "product_price": "$1.16",
    "available": true
  }, {
    "id": 25,
    "product_name": "Beauty",
    "product_price": "$2.45",
    "available": false
  }, {
    "id": 26,
    "product_name": "Iphone 13",
    "product_price": "$6.34",
    "available": false
  }, {
    "id": 27,
    "product_name": "Water Purifier",
    "product_price": "$3.05",
    "available": false
  }, {
    "id": 28,
    "product_name": "Tools",
    "product_price": "$9.39",
    "available": true
  }, {
    "id": 29,
    "product_name": "Automotive",
    "product_price": "$9.55",
    "available": false
  }, {
    "id": 30,
    "product_name": "Outdoors",
    "product_price": "$9.13",
    "available": false
  }, {
    "id": 31,
    "product_name": "Electronics",
    "product_price": "$1.16",
    "available": false
  }, {
    "id": 32,
    "product_name": "Toys",
    "product_price": "$0.10",
    "available": true
  }, {
    "id": 33,
    "product_name": "Samsung Tablet",
    "product_price": "$2.63",
    "available": false
  }, {
    "id": 34,
    "product_name": "Computers",
    "product_price": "$1.41",
    "available": false
  }, {
    "id": 35,
    "product_name": "Music",
    "product_price": "$6.70",
    "available": true
  }, {
    "id": 36,
    "product_name": "Games",
    "product_price": "$3.24",
    "available": false
  }, {
    "id": 37,
    "product_name": "Movies",
    "product_price": "$5.12",
    "available": false
  }, {
    "id": 38,
    "product_name": "Home",
    "product_price": "$1.10",
    "available": true
  }, {
    "id": 39,
    "product_name": "Sports",
    "product_price": "$7.45",
    "available": true
  }, {
    "id": 40,
    "product_name": "Home",
    "product_price": "$9.90",
    "available": true
  }, {
    "id": 41,
    "product_name": "Music",
    "product_price": "$9.38",
    "available": false
  }, {
    "id": 42,
    "product_name": "Computers",
    "product_price": "$7.86",
    "available": true
  }, {
    "id": 43,
    "product_name": "Movies",
    "product_price": "$8.03",
    "available": true
  }, {
    "id": 44,
    "product_name": "Water Purifier",
    "product_price": "$0.98",
    "available": false
  }, {
    "id": 45,
    "product_name": "Movies",
    "product_price": "$4.56",
    "available": false
  }, {
    "id": 46,
    "product_name": "Home",
    "product_price": "$2.16",
    "available": false
  }, {
    "id": 47,
    "product_name": "Water Purifier",
    "product_price": "$2.33",
    "available": true
  }, {
    "id": 48,
    "product_name": "Iphone 13",
    "product_price": "$0.68",
    "available": false
  }, {
    "id": 49,
    "product_name": "Grocery",
    "product_price": "$0.84",
    "available": false
  }, {
    "id": 50,
    "product_name": "Games",
    "product_price": "$6.72",
    "available": false
  }, {
    "id": 51,
    "product_name": "Electronics",
    "product_price": "$1.24",
    "available": false
  }, {
    "id": 52,
    "product_name": "Movies",
    "product_price": "$1.80",
    "available": false
  }, {
    "id": 53,
    "product_name": "Computers",
    "product_price": "$3.72",
    "available": false
  }, {
    "id": 54,
    "product_name": "Automotive",
    "product_price": "$6.64",
    "available": true
  }, {
    "id": 55,
    "product_name": "Samsung Tablet",
    "product_price": "$7.02",
    "available": true
  }, {
    "id": 56,
    "product_name": "Kids",
    "product_price": "$5.11",
    "available": false
  }, {
    "id": 57,
    "product_name": "Music",
    "product_price": "$9.54",
    "available": false
  }, {
    "id": 58,
    "product_name": "Sports",
    "product_price": "$3.28",
    "available": false
  }, {
    "id": 59,
    "product_name": "Clothing",
    "product_price": "$3.16",
    "available": true
  }, {
    "id": 60,
    "product_name": "Automotive",
    "product_price": "$8.25",
    "available": false
  }, {
    "id": 61,
    "product_name": "Health",
    "product_price": "$4.90",
    "available": false
  }, {
    "id": 62,
    "product_name": "Iphone 13",
    "product_price": "$6.64",
    "available": false
  }, {
    "id": 63,
    "product_name": "Games",
    "product_price": "$3.76",
    "available": false
  }, {
    "id": 64,
    "product_name": "Music",
    "product_price": "$2.14",
    "available": false
  }, {
    "id": 65,
    "product_name": "Games",
    "product_price": "$9.71",
    "available": true
  }, {
    "id": 66,
    "product_name": "Automotive",
    "product_price": "$3.48",
    "available": false
  }, {
    "id": 67,
    "product_name": "Beauty",
    "product_price": "$0.12",
    "available": true
  }, {
    "id": 68,
    "product_name": "Games",
    "product_price": "$5.29",
    "available": false
  }, {
    "id": 69,
    "product_name": "Home",
    "product_price": "$2.44",
    "available": false
  }, {
    "id": 70,
    "product_name": "Computers",
    "product_price": "$8.13",
    "available": true
  }, {
    "id": 71,
    "product_name": "Tools",
    "product_price": "$6.29",
    "available": true
  }, {
    "id": 72,
    "product_name": "Computers",
    "product_price": "$0.98",
    "available": true
  }, {
    "id": 73,
    "product_name": "Tools",
    "product_price": "$5.50",
    "available": true
  }, {
    "id": 74,
    "product_name": "Sports",
    "product_price": "$7.59",
    "available": false
  }, {
    "id": 75,
    "product_name": "Kids",
    "product_price": "$5.79",
    "available": true
  }, {
    "id": 76,
    "product_name": "Tools",
    "product_price": "$7.26",
    "available": false
  }, {
    "id": 77,
    "product_name": "Iphone 13",
    "product_price": "$7.77",
    "available": true
  }, {
    "id": 78,
    "product_name": "Clothing",
    "product_price": "$6.82",
    "available": true
  }, {
    "id": 79,
    "product_name": "Samsung Tablet",
    "product_price": "$7.80",
    "available": false
  }, {
    "id": 80,
    "product_name": "Industrial",
    "product_price": "$9.75",
    "available": true
  }, {
    "id": 81,
    "product_name": "Electronics",
    "product_price": "$0.78",
    "available": false
  }, {
    "id": 82,
    "product_name": "Jewelry",
    "product_price": "$6.58",
    "available": false
  }, {
    "id": 83,
    "product_name": "Music",
    "product_price": "$4.86",
    "available": false
  }, {
    "id": 84,
    "product_name": "Computers",
    "product_price": "$9.04",
    "available": true
  }, {
    "id": 85,
    "product_name": "Toys",
    "product_price": "$0.90",
    "available": true
  }, {
    "id": 86,
    "product_name": "Games",
    "product_price": "$6.69",
    "available": false
  }, {
    "id": 87,
    "product_name": "Tools",
    "product_price": "$4.04",
    "available": false
  }, {
    "id": 88,
    "product_name": "Computers",
    "product_price": "$9.34",
    "available": false
  }, {
    "id": 89,
    "product_name": "Industrial",
    "product_price": "$6.93",
    "available": false
  }, {
    "id": 90,
    "product_name": "Home",
    "product_price": "$9.52",
    "available": false
  }, {
    "id": 91,
    "product_name": "Water Purifier",
    "product_price": "$5.91",
    "available": true
  }, {
    "id": 92,
    "product_name": "Computers",
    "product_price": "$9.81",
    "available": true
  }, {
    "id": 93,
    "product_name": "Clothing",
    "product_price": "$1.39",
    "available": true
  }, {
    "id": 94,
    "product_name": "Toys",
    "product_price": "$8.68",
    "available": true
  }, {
    "id": 95,
    "product_name": "Clothing",
    "product_price": "$4.96",
    "available": true
  }, {
    "id": 96,
    "product_name": "Outdoors",
    "product_price": "$7.64",
    "available": true
  }, {
    "id": 97,
    "product_name": "Health",
    "product_price": "$5.22",
    "available": true
  }, {
    "id": 98,
    "product_name": "Shoes",
    "product_price": "$4.16",
    "available": true
  }, {
    "id": 99,
    "product_name": "Music",
    "product_price": "$7.98",
    "available": true
  }, {
    "id": 100,
    "product_name": "Games",
    "product_price": "$9.81",
    "available": false
  }]